CREATE DATABASE db_logreg;

DROP TABLE IF EXISTS tb_users;

CREATE TABLE tb_users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
